"""add file_path to books

Revision ID: df185b25ee76
Revises: b77aaee268db
Create Date: 2026-06-06 12:06:28.247749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df185b25ee76'
down_revision: Union[str, Sequence[str], None] = 'b77aaee268db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('file_path', sa.String(), nullable=False), schema='librarian')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'file_path', schema='librarian')
    # ### end Alembic commands ###
