"""Add embedding field to tag model

Revision ID: 1b6d9ac16dc9
Revises: 7426b1b6f9a6
Create Date: 2026-06-16 14:50:17.026463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '1b6d9ac16dc9'
down_revision: Union[str, Sequence[str], None] = '7426b1b6f9a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'isbn',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               schema='librarian')
    op.add_column('tags', sa.Column('embedding', Vector(dim=1536), nullable=False), schema='librarian')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'embedding', schema='librarian')
    op.alter_column('books', 'isbn',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               schema='librarian')
    # ### end Alembic commands ###
