"""add file and book relationship

Revision ID: 2e479694a2dd
Revises: df185b25ee76
Create Date: 2026-06-06 22:19:43.367590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e479694a2dd'
down_revision: Union[str, Sequence[str], None] = 'df185b25ee76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='librarian'
    )
    op.add_column('books', sa.Column('file_id', sa.Integer(), nullable=False), schema='librarian')
    op.create_foreign_key(None, 'books', 'files', ['file_id'], ['id'], source_schema='librarian', referent_schema='librarian', ondelete='RESTRICT')
    op.drop_column('books', 'file_path', schema='librarian')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False), schema='librarian')
    op.drop_constraint(None, 'books', schema='librarian', type_='foreignkey')
    op.drop_column('books', 'file_id', schema='librarian')
    op.drop_table('files', schema='librarian')
    # ### end Alembic commands ###
