"""adding document model table

Revision ID: 7e7190be74c2
Revises: 966bc5855910
Create Date: 2026-06-11 14:52:59.317507

"""
from typing import Sequence, Union
from pgvector.sqlalchemy import Vector
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e7190be74c2'
down_revision: Union[str, Sequence[str], None] = '966bc5855910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('embedding', Vector(dim=1536), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['librarian.files.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['librarian.jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='librarian'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents', schema='librarian')
    # ### end Alembic commands ###
