"""tags for books

Revision ID: 7eb1b6b25863
Revises: df185b25ee76
Create Date: 2026-06-06 23:19:22.601893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eb1b6b25863'
down_revision: Union[str, Sequence[str], None] = 'df185b25ee76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='librarian'
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='librarian'
    )
    op.create_table('book_tags',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['librarian.books.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['librarian.tags.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'tag_id'),
    schema='librarian'
    )
    op.add_column('books', sa.Column('file_id', sa.Integer(), nullable=False), schema='librarian')
    op.create_foreign_key(None, 'books', 'files', ['file_id'], ['id'], source_schema='librarian', referent_schema='librarian', ondelete='RESTRICT')
    op.drop_column('books', 'file_path', schema='librarian')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False), schema='librarian')
    op.drop_constraint(None, 'books', schema='librarian', type_='foreignkey')
    op.drop_column('books', 'file_id', schema='librarian')
    op.drop_table('book_tags', schema='librarian')
    op.drop_table('tags', schema='librarian')
    op.drop_table('files', schema='librarian')
    # ### end Alembic commands ###
