"""add jobs

Revision ID: e3b75881f7f1
Revises: 7eb1b6b25863
Create Date: 2026-06-06 23:32:12.193403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3b75881f7f1'
down_revision: Union[str, Sequence[str], None] = '7eb1b6b25863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='statusenum'), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['librarian.files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='librarian'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs', schema='librarian')
    # ### end Alembic commands ###
